name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git
        run: |
          git config user.name "Velavaaa"
          git config user.email "murugaqwe63@gmail.com"

      - name: Install bump2version
        run: pip install bump2version

      - name: Delete existing tag
        run: |
          git tag -d v0.1.2 || true
          git push origin :refs/tags/v0.1.2 || true

      - name: Commit changes
        run: |
          git add .
          git commit -m "Committing changes before bumping version" || echo "No changes to commit"

      - name: Bump version
        run: bump2version --new-version 0.1.3 patch

      - name: Pull latest changes
        run: git pull origin main

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
